const assert = require('node:assert/strict');
const MusicLibrary = require('../js/music-library.js');
const memory = new Map();
const storage = { getItem: k => memory.get(k), setItem: (k, v) => memory.set(k, v) };
const library = new MusicLibrary(storage);
library.favorite('slow-orbit');
library.banish('slow-orbit');
assert.deepEqual(library.playable('favorites'), []);
assert(!library.playable('nocturnal').includes('slow-orbit'));
const custom = library.create('<my night>');
library.add(custom.id, 'slow-orbit');
library.add(custom.id, 'slow-orbit');
library.add(custom.id, 'undertow');
library.add(custom.id, 'missing');
assert.deepEqual(library.playable(custom.id), ['undertow']);
library.banish('slow-orbit');
assert.deepEqual(library.playable(custom.id), ['slow-orbit', 'undertow']);
library.move(custom.id, 'undertow', -1);
library.settings.repeat = 'off';
library.save();
const restored = new MusicLibrary(storage);
assert.deepEqual(restored.playable(custom.id), ['undertow', 'slow-orbit']);
assert.equal(restored.custom[0].name, '<my night>');
assert.equal(restored.settings.repeat, 'off');
restored.remove(custom.id, 'undertow');
assert.deepEqual(restored.playable(custom.id), ['slow-orbit']);
restored.trackIds('nocturnal').forEach(id => restored.banish(id));
assert.deepEqual(restored.playable('nocturnal'), []);
const corrupt = new MusicLibrary({ getItem: () => '{broken' });
assert.equal(corrupt.playable('nocturnal').length, 6);
const malformed = new MusicLibrary({getItem:()=>JSON.stringify({favorites:['slow-orbit','missing'],banished:['missing'],custom:[null,{id:'nocturnal'},{id:'custom-test',tracks:['undertow','missing','undertow']},{id:'custom-test',tracks:[]}],settings:{volume:99,repeat:'bad'}})});
assert.equal(malformed.custom.length, 1);
assert.deepEqual(malformed.playable('custom-test'), ['undertow']);
assert.equal(malformed.settings.volume, 1);
assert.equal(malformed.settings.repeat, 'all');
assert.equal(new MusicLibrary({getItem:()=>null,setItem:()=>{throw Error('full')}}).save(), false);
console.log('Music library: ban/restore, favorite, custom order, reload, malformed storage, and unavailable persistence passed.');

// Built-in playlists remain separate; existing local preferences can include either catalog.
const both = new MusicLibrary(storage);
assert.equal(both.trackIds('nocturnal').length, 6);
assert.equal(both.trackIds('dark-pulse').length, 6);
assert(!both.trackIds('nocturnal').some(id => both.trackIds('dark-pulse').includes(id)));
both.favorite('iron-pulse'); both.banish('iron-pulse');
assert(!both.playable('dark-pulse').includes('iron-pulse'));
assert.equal(both.playable('nocturnal').length, 6);
both.banish('iron-pulse'); both.favorite('iron-pulse'); both.add(both.custom[0].id, 'iron-pulse'); both.save();
const combined = new MusicLibrary(storage);
assert(combined.playable(combined.custom[0].id).includes('iron-pulse'));
assert(combined.playable('favorites').includes('iron-pulse'));
assert(combined.track('iron-pulse').url === 'audio/dark-pulse/iron-pulse.mp3');
console.log('Both built-in playlists, cross-catalog favorites, bans, custom lists and saved preferences passed.');
